package org.example.util;

public enum Tempo {

    GRAVE, LENTO, LARGO, LARGHETTO, ADAGIO, ADAGIETTO, ANDANTE, ANDANTINO,
    MODERATO, ALLEGRETTO, ALLEGRO, VIVACE, VIVO, PRESTO, PRESTISSIMO, RUBATO

}

